//! A peephole pass over generated bytecode, run only when optimizing:
//!
//! * Jump threading: a jump to an unconditional `Jump` goes straight to that
//!   jump's target.
//! * Push/pop removal: a push with no side effect followed by `Pop` is
//!   deleted, unless a jump targets either instruction.
//!
//! Deleting instructions shifts indices, so every jump target is remapped.

use std::collections::HashSet;

use crate::backend::bytecode::{Chunk, Op, Program};

/// Optimizes every chunk in place; returns the number of instructions removed.
#[tracing::instrument(level = "debug", skip_all)]
pub fn optimize(program: &mut Program) -> usize {
    let mut removed = 0;
    for chunk in &mut program.functions {
        loop {
            thread_jumps(chunk);
            let n = eliminate_push_pop(chunk);
            removed += n;
            if n == 0 {
                break;
            }
        }
    }
    tracing::debug!(removed, "peephole optimization complete");
    removed
}

/// Retargets jumps that land on an unconditional `Jump`, following chains.
fn thread_jumps(chunk: &mut Chunk) {
    let len = chunk.code.len();
    let resolve = |mut target: usize| -> usize {
        let mut guard = 0;
        while guard < len {
            match chunk.code.get(target) {
                Some(Op::Jump(next)) if *next != target => {
                    target = *next;
                    guard += 1;
                }
                _ => break,
            }
        }
        target
    };
    // Resolve every target before changing any.
    let resolved: Vec<(usize, usize)> = chunk
        .code
        .iter()
        .enumerate()
        .filter_map(|(i, op)| op.jump_target().map(|t| (i, resolve(t))))
        .collect();
    for (i, target) in resolved {
        if let Some(t) = chunk.code[i].jump_target_mut() {
            *t = target;
        }
    }
}

/// Removes pure `push; pop` pairs and remaps jump targets. Returns the number
/// of instructions removed.
fn eliminate_push_pop(chunk: &mut Chunk) -> usize {
    let targets = jump_targets(chunk);
    let n = chunk.code.len();
    let mut remove = vec![false; n];

    let mut i = 0;
    while i + 1 < n {
        let is_pure_push = matches!(
            chunk.code[i],
            Op::PushInt(_)
                | Op::PushFloat(_)
                | Op::PushBool(_)
                | Op::PushUnit
                | Op::PushStr(_)
                | Op::LoadLocal(_)
        );
        let pop_follows = matches!(chunk.code[i + 1], Op::Pop);
        // A jump to either instruction would lose its target.
        if is_pure_push && pop_follows && !targets.contains(&i) && !targets.contains(&(i + 1)) {
            remove[i] = true;
            remove[i + 1] = true;
            i += 2;
        } else {
            i += 1;
        }
    }

    let removed = remove.iter().filter(|&&r| r).count();
    if removed == 0 {
        return 0;
    }

    // Old index → new index. A removed instruction maps to the next survivor.
    let mut new_index = vec![0usize; n + 1];
    let mut next = 0;
    for (old, &gone) in remove.iter().enumerate() {
        new_index[old] = next;
        if !gone {
            next += 1;
        }
    }
    new_index[n] = next;

    let old_code = std::mem::take(&mut chunk.code);
    for (old, op) in old_code.into_iter().enumerate() {
        if remove[old] {
            continue;
        }
        chunk.code.push(remap(op, &new_index));
    }
    removed
}

/// The indices that some jump targets.
fn jump_targets(chunk: &Chunk) -> HashSet<usize> {
    chunk.code.iter().filter_map(Op::jump_target).collect()
}

/// `op` with its jump target, if any, mapped through `new_index`.
fn remap(mut op: Op, new_index: &[usize]) -> Op {
    if let Some(t) = op.jump_target_mut() {
        *t = new_index[*t];
    }
    op
}

#[cfg(test)]
mod tests;
